package edu.fcpc.polaroid.packets;

public enum PackageStatus {
    LOGIN, REGISTER, PICTURE,

    LOGIN_RESPONSE_OK, LOGIN_RESPONSE_FAIL,

    REGISTER_RESPONSE_OK, REGISTER_RESPONSE_FAIL,

    PICTURE_RESPONSE_OK, PICTURE_RESPONSE_FAIL,

    HOSTNAME_NOT_FOUND, NO_SERVER_FOUND, NETWORK_BYPASS,

    SERVER_PING
}
